<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_installer
 *
 * @copyright   Copyright (C) 2005 - 2016 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

/**
 * Extension Manager Install Model
 *
 * @since  1.5
 */
class InstallerModelInstaller extends JModelLegacy
{

  /**
   * [initialize description]
   * @return [type] [description]
   */
  public function initialize( $package, $params ){

    // Stage Model
      $this->set( 'package', $package );
      $this->set( 'params', new JRegistry($params) );

    // Reset Installer
      if( !$this->reset() ){
        return false;
      }

    // Create Installer
      if( !$this->createInstaller() ){
        return false;
      }

    // Prepare Session
      JFactory::getApplication()->setUserState('com_installer.ajaxurl', '/media/com_installer/standalone/installer.php');
      JFactory::getApplication()->setUserState('com_installer.returnurl', 'index.php?option=com_installer&task=installer.finalise');

    // Success
      return true;

  }

  public function finalise(){

    die(__LINE__.': '.__FILE__);

  }

  /**
   * [reset description]
   * @return [type] [description]
   */
  public function reset(){

    // Reset Session
      JFactory::getApplication()->setUserState('com_installer.password', null);
      JFactory::getApplication()->setUserState('com_installer.filesize', null);
      JFactory::getApplication()->setUserState('com_installer.ajaxurl', null);
      JFactory::getApplication()->setUserState('com_installer.returnurl', null);

    // Complete
      return true;

  }

  /**
   * [install description]
   * @return [type] [description]
   */
  public function status(){

    die(__LINE__.': '.__FILE__);

    return true;
  }

  /**
   * [install description]
   * @return [type] [description]
   */
  public function install(){

    die(__LINE__.': '.__FILE__);

    return true;
  }

  /**
   * [getInstallerProvider description]
   * @return [type] [description]
   */
  public function getInstallerProvider(){
    include(JPATH_ADMINISTRATOR . '/components/com_installer/standalone/provider/standaloneProvider.php');
    include(JPATH_ADMINISTRATOR . '/components/com_installer/standalone/provider/akeeba.php');
    return new JInstallerStandaloneProviderAkeeba( $this->get('package'), $this->get('params') );
  }

  /**
   * [createInstaller description]
   * @return [type] [description]
   */
  public function createInstaller(){

    // Stage
      $app = JFactory::getApplication();

    // Copy Installer to Media
      if(
        is_readable(JPATH_ADMINISTRATOR . '/components/com_installer/standalone/installer.php')
        &&
        (
        is_dir(JPATH_ROOT . '/media/com_installer/standalone/')
        ||
        @mkdir(JPATH_ROOT . '/media/com_installer/standalone/', 0755, true)
        )
        &&
        is_writeable(JPATH_ROOT . '/media/com_installer/standalone/')
        ){

        // Remove Existing
          if( is_readable(JPATH_ROOT . '/media/com_installer/standalone/installer.php') ){
            @unlink(JPATH_ROOT . '/media/com_installer/standalone/installer.php');
          }
          if( is_readable(JPATH_ROOT . '/media/com_installer/standalone/installer.php') ){
            $app->enqueueMessage(JText::_('COM_INSTALLER_STANDALONE_NOT_WRITABLE'), 'error');
            return false;
          }

        // Prepare build instructions
        // TODO: This is ugly and needs a class
          $installerBuildList = array(
            array(
              "",
              "/*",
              "  Generated by " . __FILE__,
              "  " . gmdate('Y-m-d H:i:s'),
              "*/",
              "",
              "if( !preg_match('/media.com_installer.standalone/', __DIR__) ){ exit; }",
              ""
              )
            );

        // Load installer build extensions
        // TODO: This is hardcoded and needs logic
          $provider = $this->getInstallerProvider();
          $provider->appendBuildList( $installerBuildList );

        // Append Main Runtime to List
          $installerBuildList[] = JPATH_ADMINISTRATOR . '/components/com_installer/standalone/installer.php';

        // Build installer file
        // TODO: There is probably a good standard for replacing this
          $fh = fopen( JPATH_ROOT . '/media/com_installer/standalone/installer.php', 'w+' );
          if( $fh ){
            $bytesWritten = 0;
            foreach( $installerBuildList AS $item ){
              if( !$bytesWritten ){
                $tmpBuffer = '<?php';
                fwrite( $fh, $tmpBuffer );
                $bytesWritten += strlen( $tmpBuffer );
              }
              if( is_array($item) ){
                fwrite( $fh, "\n\n");
                fwrite( $fh, "/*\n  Code Block \n*/");
                fwrite( $fh, "\n\n");
                fwrite( $fh, implode("\n", $item) );
              }
              else if( is_string($item) && is_readable($item) ){
                $fa = fopen( $item, 'r' );
                if( $fa ){
                  fwrite( $fh, "\n\n");
                  fwrite( $fh, "/*\n  Source\n  ".$item.' / '.filesize($item)."\n*/");
                  fwrite( $fh, "\n\n");
                  $bytesRead = 0;
                  while( !feof($fa) && $buffer = fread($fa, 1024 * 10) ){
                    if( $bytesRead == 0 && preg_match('/^\<\?(php|)[\s\r\n]+/',$buffer) ){
                      $bytesRead += strlen( $buffer );
                      $tmpBuffer = preg_replace('/^\<\?(php|)[\s\r\n]+/', '', $buffer);
                      $bytesWritten += strlen( $tmpBuffer );
                      $buffer = $tmpBuffer;
                    }
                    else {
                      $bytesRead += strlen( $buffer );
                      $bytesWritten += strlen( $buffer );
                    }
                    fwrite( $fh, $buffer );
                  }
                  fclose( $fa );
                }
                else {
                  $app->enqueueMessage(JText::_('COM_INSTALLER_STANDALONE_BUILD_FAILED'), 'error');
                  return false;
                }
              }
            }
            fclose( $fh );
          }
          else {
            $app->enqueueMessage(JText::_('COM_INSTALLER_STANDALONE_NOT_WRITABLE'), 'error');
            return false;
          }
          if( !is_readable(JPATH_ROOT . '/media/com_installer/standalone/installer.php') ){
            $app->enqueueMessage(JText::_('COM_INSTALLER_STANDALONE_NOT_WRITABLE'), 'error');
            return false;
          }

      }
      else {
        $app->enqueueMessage(JText::_('COM_INSTALLER_STANDALONE_NOT_WRITABLE'), 'error');
        return false;
      }

    // Complete
      return true;

  }

}
